# Generated by Django 5.1.2 on 2025-01-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_commission_profile_request_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='students_interested',
        ),
    ]
