# Generated by Django 5.1.2 on 2025-01-13 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_commission_students_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='name',
            field=models.CharField(default='Unnamed', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='commissioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
