# Generated by Django 5.1.2 on 2025-01-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_commission_name_alter_commission_commissioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('commissioner', 'Commissioner')], default='student', max_length=20),
        ),
    ]
