# Generated by Django 5.1.2 on 2025-01-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='name',
        ),
    ]
